version: '3.8'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    container_name: 'pgsql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg-data: